# Generated by Django 2.1.3 on 2018-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentgroup',
            name='equipment_group_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'TopDriver'), (1, 'Propeller'), (2, 'Generator')], null=True, verbose_name='Type of equipment group'),
        ),
    ]
