# Generated by Django 2.1.3 on 2018-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181212_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Bearing'), (1, 'Gear'), (2, 'Rotor'), (3, 'Stator'), (4, 'Shaft')], max_length=64, null=True, verbose_name='Type of component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='component',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='datacollector',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='datacollector',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='equipmentgroup',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='equipmentgroup',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Motor'), (1, 'GearBox'), (2, 'Engine')], null=True, verbose_name='Type of machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='cr_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='md_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
    ]
