# Generated by Django 2.1.3 on 2018-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181212_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Bearing'), (1, 'Gear'), (2, 'Rotor'), (3, 'Stator'), (4, 'Shaft')], null=True, verbose_name='Type of component'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Accelerator'), (1, 'CurrentProbe'), (2, 'TacoMeter')], null=True, verbose_name='Type of sensor'),
        ),
    ]
