# Generated by Django 2.1.3 on 2018-12-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181212_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_day', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('description', models.TextField(verbose_name='Warning description')),
                ('equipment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.EquipmentGroup')),
            ],
        ),
    ]
