# Generated by Django 2.1.3 on 2018-12-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_warninglog_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='parent_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Components', to='assets.Machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='parent_equipment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Machines', to='assets.EquipmentGroup'),
        ),
        migrations.AlterField(
            model_name='measurepoint',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeasurePoints', to='assets.Machine'),
        ),
    ]
